// ============================================================
// LUNARA OS — Content Atom → Content Family Engine
// Foundation: LUNARA MASTER BIBLE v2.0, §10
// Purpose: Define the structure for content transformation
// NOTE: Actual content is generated by Muse (AI) at runtime
// ============================================================

import type { ChannelId } from './channels';

export interface ContentAtom {
  atom_id: string;
  core_insight: string;           // The one audience problem (in English)
  target_audience_problem: string; // What pain point it addresses
  source_opportunity_id: string;   // Which Nyx opportunity spawned this
  created_by: string;              // Agent ID (usually "sage")
  created_at: number;
  confidence: number;              // 0-1
}

export interface ContentVariant {
  channel_id: ChannelId;
  title: string;          // Generated by Muse (in English)
  hook: string;           // Generated by Muse
  description: string;    // Generated by Muse
  format: string;         // e.g., "carousel (5 slides)", "short video (30s)"
  cta: string;            // Call-to-action
  language: string;       // "en" by default, can be localized later
}

export interface ContentFamily {
  family_id: string;
  atom: ContentAtom;
  variants: ContentVariant[];  // Empty initially, filled by Muse
  created_at: number;
  status: "draft" | "generating" | "approved" | "published";
  generated_by: string;        // Agent ID (usually "muse")
}

// §10: Adaptation rules per channel (these guide Muse's generation)
export const CHANNEL_ADAPTATION_RULES: Record<ChannelId, { 
  tone: string; 
  format: string; 
  cta_style: string;
  language: string;
}> = {
  human_mind: {
    tone: "analytical, expert, deep",
    format: "long text or carousel",
    cta_style: "psychological test or article",
    language: "en"
  },
  love: {
    tone: "emotional, personal, shareable",
    format: "short video or image with text",
    cta_style: "share with someone who needs this",
    language: "en"
  },
  astrology: {
    tone: "identity-focused, habit-forming",
    format: "daily horoscope or zodiac ranking",
    cta_style: "check your sign",
    language: "en"
  },
  tarot: {
    tone: "interactive, mystical, intriguing",
    format: "Pick-a-card video or post",
    cta_style: "pick a card in Lunara App",
    language: "en"
  },
  mystery: {
    tone: "story format, intrigue, curiosity",
    format: "long story or series",
    cta_style: "learn more / next episode",
    language: "en"
  },
  lunara: {
    tone: "product-focused, CTA-driven",
    format: "Mini App link, premium offer",
    cta_style: "open Lunara / get reading",
    language: "en"
  }
};

// This is the function that will be called by Muse (or AI) to generate content
export async function generateContentFamily(
  atom: ContentAtom, 
  aiGenerator: (atom: ContentAtom, rules: typeof CHANNEL_ADAPTATION_RULES) => Promise<ContentVariant[]>
): Promise<ContentFamily> {
  const variants = await aiGenerator(atom, CHANNEL_ADAPTATION_RULES);
  
  return {
    family_id: `family_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    atom,
    variants,
    created_at: Date.now(),
    status: "draft",
    generated_by: "muse"
  };
}